<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * IgredientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IgredientRepository extends EntityRepository implement Repository
{
}
